image: Visual Studio 2017
environment:
  matrix:
    - nodejs_version: "10.1"
    - nodejs_version: "10.3"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
test_script:
  - node --version
  - npm --version
  - npm run lint
  - npm run coverage
  - npm run codecov
build: off
